import { Footer } from '@/components/footer';
import { Header } from '@/components/header';
import { routing } from '@/i18n/routing';
import { getPages } from '@/lib/services';
import type { Metadata } from 'next';
import { hasLocale, NextIntlClientProvider } from 'next-intl';
import { Poppins } from 'next/font/google';
import { notFound } from 'next/navigation';
import '../globals.css';

const poppins = Poppins({
	display: 'swap',
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	subsets: ['latin'],
	variable: '--font-poppins',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = async ({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) => {
	const { locale } = await params;

	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}

	const pages = await getPages(locale);
	const page = pages[0];

	return (
		<html lang={locale}>
			<body className={`${poppins.variable} ${poppins.className} antialiased`}>
				<Header data={page.head_menu} />
				<NextIntlClientProvider>{children}</NextIntlClientProvider>
				<Footer data={page.footer} />
			</body>
		</html>
	);
};

export default RootLayout;
